# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MatchTransition.xcworkspace -scheme MatchTransition-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
